# Generated by Django 2.0.6 on 2018-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='account',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
